title: Bennett Godinho-Nelson
email: bennettgodinhonelson@gmail.com
description: >- 
  This is Bennett Godinho-Nelson's professional website. It is created with jekyll and cvless Ruby gems. Enjoy!
url: "https://bennettgn.github.io" 
baseurl: "" 
github_username:  BennettGN

# site settings
taglong: Software Engineer
tagshort: Software Engineer

# Build settings
theme: cvless
  
# author settings
author:
  name: Bennett Godinho-Nelson
  email: bennettgodinhonelson@gmail.com
photo: assets/files/godinho.jpg
address: Columbus, OH
phone: +1 937 794 2186

#Stats
stats:
  undergrad-graduation: May 2025
  undergrad-gpa: 3.71
  grad-graduation: May 2026
  grad-gpa: 4.0
  clarkstate-grad: May 2022
  clarkstate-gpa: 3.96
# social media links
social:
  linkedin: bennett-godinho-nelson-013656247
  github: BennettGN

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - cvless

sass:
  sourcemap: never

pagination:
  enabled: true